//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capcha
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountData
    {
        public string idUser { get; set; }
        public string idNameNote { get; set; }
        public string idSpisok { get; set; }
        public string idDescriptiom { get; set; }
    
        public virtual Desc Desc { get; set; }
        public virtual Note_Table Note_Table { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual Spisok Spisok { get; set; }
    }
}
