//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capcha
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Note_Table()
        {
            this.AccountData = new HashSet<AccountData>();
        }
    
        public string idNameNote { get; set; }
        public string Description { get; set; }
        public string FileChoosen { get; set; }
        public string Date { get; set; }
        public string Completed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountData> AccountData { get; set; }
    }
}
